PROFILE = {
    "first_name": "Unika",
    "last_name": "Bista",
    "name": "Unika Bista",
    "email": "unika.bista0@gmail.com",
    "phone": "3183508760",
    "phone_formatted": "+1-318-350-8760",
    "location": "San Francisco, CA",
    "city": "San Francisco",
    "state": "California",
    "state_abbr": "CA",
    "country": "United States",
    "linkedin": "https://www.linkedin.com/in/unika-bista-50139033a/",
    "github": "",
    "website": "",
    "school": "University of Louisiana at Monroe",
    "school_greenhouse": "University of Louisiana - Monroe",
    "degree": "Bachelor's Degree",
    "discipline": "Computer Science",
    "graduation_month": "May",
    "graduation_year": "2027",
    "gpa": "",
    "work_authorized": True,
    "requires_sponsorship": False,
    "pronouns": "She/her",
    "gender": "Female",
    "race": "Asian",
    "veteran": False,
    "disability": False,
    "how_heard": "Job board",
    "project_blurb": "At Xerox I built and deployed an AI agent across Microsoft 365 to automate reporting for senior leadership at a Fortune 500 company. I also built Dristi, a voice-controlled AI app (99% uptime, 40% faster task completion) that won 2nd at ULM Hawkathon and 3rd at Nexus Technology Cup, and SATHI, an agentic career assistant using RAG and prompt engineering.",
}
